version: "3.3"
volumes:
  db-store:
  php-fpm-socket:
services:
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    container_name: "blog-nginx"
    ports:
      - "8080:80"
      - "1443:443"
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - ./html:/var/www/html
      - ./docker/log/nginx:/var/log/nginx
    environment:
      - VIRTUAL_HOST=blog.toutounode.localhost
      - PHP_APP_HOST=php
    depends_on:
      - php
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: "blog-php"
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - ./html:/var/www/html
      - ./docker/log/php:/var/log/php
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=itu-blog
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - APP_DEBUG=true
  mysql:
    image: mysql:8
    container_name: blog-mysql
    restart: always
    environment:
      MYSQL_DATABASE: itu-blog
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
      TZ: "Asia/Tokyo"
    ports:
      - "13316:3306"
    volumes:
      - db-store:/var/lib/mysql
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
      - ./docker/log/mysql:/var/log/mysql

networks:
  default:
    external:
      name: itu_shared
